### ISSUE TITLE
Autoloading classes

### ISSUE THREAD

**Issue by akinyeleolubodun** [popphp/popphp-tutorial#1]
All classes are autoloaded in this great sample. How can one replicate this same structure in projects that uses the downloaded version (.zip) of the framework? Or using the loader class is the appropriate thing to do?

**Comment by nicksagona** [comment]
In the skeleton example, it relies on Composer, so if you clone or download this repo, from the repo folder, you can just run:

``` console
$ composer install
```

and it'll install the few required components for you (not the whole framework.)

The other option if you want to use the full standalone downloaded version from the website, is to copy the `vendor` folder from the downloaded version into this repo and it should work from there as well (and you'll have the whole framework in that case.)
